name: Create Release
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - 7**
      - 6**
      - 5**
      - 4**
jobs:
  build-release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.title, 'Release ')
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo '${{ github.head_ref }}' | sed 's/v/::set-output name=VERSION::/'
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - id: compile-membrane
        name: Compile Membrane
        run: |
          git status
